dezorafurniture/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("blogs/", views.blog, name="blog"),
    path("products/", views.product, name="product"),
    path("contact/", views.contact, name="contact"),

    path("wish-list/", views.wish_list, name="wish_list"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout",)
]

web/models.py
from django.db import models
from tinymce.models import HTMLField


# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=180)
    slug = models.SlugField()
    date = models.DateField(auto_now_add=True)
    description = HTMLField()

    def __str__(self):
        return self.title

web/views.py
from django.shortcuts import render


def index(request):
    context = {"is_index": True}
    return render(request, "web/index.html", context)

def about(request):
    context = {
        "is_about":True
    }
    return render(request, "web/about.html", context)

def blog(request):
    context = {
        "is_blog":True
    }
    return render(request, "web/blog.html", context)

def product(request):
    context = {
        "is_product":True
    }
    return render(request, "web/product.html", context)

def contact(request):
    context = {
        "is_contact":True
    }
    return render(request, 'web/contact.html', context)


def wish_list(request):
    return render(request, 'web/wish-list.html')

def cart(request):
    return render(request, "web/cart.html")

def checkout(request):
    return render(request, "web/checkout.html")

templates/web/contact.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

        <!-- tf-add-cart-success -->
        <div class="tf-add-cart-success">
            <div class="tf-add-cart-heading">
                <h5>Shopping Cart</h5>
                <i class="icon icon-close tf-add-cart-close"></i>
            </div>
            <div class="tf-add-cart-product">
                <div class="image">
                    <img class=" ls-is-cached lazyloaded" data-src="images/products/womens/women-3.jpg" alt="" src="images/products/womens/women-3.jpg">
                </div>
                <div class="content">
                    <div class="text-title">
                        <a class="link" href="product-detail.html">Biker-style leggings</a>
                    </div>
                    <div class="text-caption-1 text-secondary-2">Green, XS, Cotton</div>
                    <div class="text-title">$68.00</div>
                </div>
            </div>
            <a href="{% url 'web:cart' %}" class="tf-btn w-100 btn-fill radius-4"><span class="text text-btn-uppercase">View cart</span></a>
        </div>
        <!-- /tf-add-cart-success -->

        <!-- page-title -->
        <div class="page-title" style="background-image: url(images/section/page-title.jpg);">
            <div class="container-full">
                <div class="row">
                    <div class="col-12">
                        <h3 class="heading text-center">Contact Us</h3>
                        <ul class="breadcrumbs d-flex align-items-center justify-content-center">
                            <li>
                                <a class="link" href="index.html">Homepage</a>
                            </li>
                            <li>
                                <i class="icon-arrRight"></i>
                            </li>
                            <li>
                                <a class="link" href="#">Pages</a>
                            </li>
                            <li>
                                <i class="icon-arrRight"></i>
                            </li>
                            <li>
                                Contact Us
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page-title -->

        <!-- Store locations -->
        <section class="flat-spacing">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="contact-us-map">
                            <div class="wrap-map">
                                <div id="map-contact" class="map-contact"  data-map-zoom="16" data-map-scroll="true"></div>
                            </div>
                            <div class="right">
                                <h4>Information</h4>
                                <div class="mb_20">
                                    <div class="text-title mb_8">Phone:</div>
                                    <p class="text-secondary">+1 666 234 8888</p>
                                </div>
                                <div class="mb_20">
                                    <div class="text-title mb_8">Email:</div>
                                    <p class="text-secondary">dezora@gmail.com</p>
                                </div>
                                <div class="mb_20">
                                    <div class="text-title mb_8">Address:</div>
                                    <p class="text-secondary">2163 Phillips Gap Rd, West Jefferson, North Carolina, United States</p>
                                </div>
                                <div>
                                    <div class="text-title mb_8">Open Time:</div>
                                    <p class="mb_4 open-time">
                                        <span class="text-secondary">Mon - Sat:</span> 7:30am - 8:00pm PST
                                    </p>
                                    <p class="open-time">
                                        <span class="text-secondary">Sunday:</span> 9:00am - 5:00pm PST
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- /Store locations -->

        <!-- Get In Touch -->
        <section class="flat-spacing pt-0">
            <div class="container">
                <div class="heading-section text-center">
                    <h3 class="heading">Get In Touch</h3>
                    <p class="subheading">Use the form below to get in touch with the sales team</p>
                </div>
                <form id="contactform" action="" method="post" class="form-leave-comment">
                    <div class="wrap">
                        <div class="cols">
                            <fieldset class="">
                                <input class="" type="text" placeholder="Your Name*" name="name" id="name" tabindex="2" value="" aria-required="true" required="">
                            </fieldset>
                            <fieldset class="">
                                <input class="" type="email" placeholder="Your Email*" name="email" id="email" tabindex="2" value="" aria-required="true" required="">
                            </fieldset>
                        </div>
                        <fieldset class="">
                            <textarea name="message" id="message" rows="4" placeholder="Your Message*" tabindex="2" aria-required="true" required=""></textarea>
                        </fieldset>
                    </div>
                    <div class="button-submit send-wrap">
                        <button class="tf-btn btn-fill" type="submit">
                            <span class="text text-button">Send message</span>
                        </button>
                    </div>
                </form>
            </div>
        </section>
        <!-- /Get In Touch -->

       {% endblock %}

templates/web/partials/footer.html
{% load static %}
<!-- Footer -->
<footer id="footer" class="footer">
    <div class="footer-wrap">
        <div class="footer-body">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="footer-infor">
                            <div class="footer-logo">
                                <a href="index.html">
                                    <img src="{% static 'web/images/logo/logo.png' %}" height="50" alt="">
                                </a>
                            </div>
                            <div class="footer-address">
                                <p>549 Oak St.Crystal Lake, IL 60014</p>
                                <a href="contact.html" class="tf-btn-default fw-6">GET DIRECTION<i class="icon-arrowUpRight"></i></a>
                            </div>
                            <ul class="footer-info">
                                <li>
                                    <i class="icon-mail"></i>
                                    <p>dezora@gmail.com</p>
                                </li>
                                <li>
                                    <i class="icon-phone"></i>
                                    <p>315-666-6688</p>
                                </li>
                            </ul>
                            <ul class="tf-social-icon">
                                <li><a href="#" class="social-facebook"><i class="icon icon-fb"></i></a></li>
                                <li><a href="#" class="social-twiter"><i class="icon icon-x"></i></a></li>
                                <li><a href="#" class="social-instagram"><i class="icon icon-instagram"></i></a></li>
                                <li><a href="#" class="social-tiktok"><i class="icon icon-tiktok"></i></a></li>
                                <li><a href="#" class="social-amazon"><i class="icon icon-amazon"></i></a></li>
                                <li><a href="#" class="social-pinterest"><i class="icon icon-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="footer-menu">
                            <div class="footer-col-block">
                                <div class="footer-heading text-button footer-heading-mobile">
                                    Infomation
                                </div>
                                <div class="tf-collapse-content">
                                    <ul class="footer-menu-list">
                                        <li class="text-caption-1">
                                            <a href="about-us.html" class="footer-menu_item">About Us</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="#" class="footer-menu_item">Our Stories</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="#" class="footer-menu_item">Size Guide</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="contact.html" class="footer-menu_item">Contact us</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="#" class="footer-menu_item">Career</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="my-account.html" class="footer-menu_item">My Account</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="footer-col-block">
                                <div class="footer-heading text-button footer-heading-mobile">
                                    Customer Services
                                </div>
                                <div class="tf-collapse-content">
                                    <ul class="footer-menu-list">
                                        <li class="text-caption-1">
                                            <a href="#" class="footer-menu_item">Shipping</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="#" class="footer-menu_item">Return & Refund</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="#" class="footer-menu_item">Privacy Policy</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="term-of-use.html" class="footer-menu_item">Terms & Conditions</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="FAQs.html" class="footer-menu_item">Orders FAQs</a>
                                        </li>
                                        <li class="text-caption-1">
                                            <a href="{% url 'web:wish_list' %}" class="footer-menu_item">My Wishlist</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="footer-col-block">
                            <div class="footer-heading text-button footer-heading-mobile">
                                Newletter
                            </div>
                            <div class="tf-collapse-content">
                                <div class="footer-newsletter">
                                    <p class="text-caption-1">Sign up for our newsletter and get 10% off your first purchase</p>
                                    <form class="form-newsletter subscribe-form"  action="#" method="post" accept-charset="utf-8" data-mailchimp="true">
                                        <div class="subscribe-content">
                                            <fieldset class="email">
                                                <input type="email" name="email-form" class="subscribe-email" placeholder="Enter your e-mail" tabindex="0" aria-required="true">
                                            </fieldset>
                                            <div class="button-submit">
                                                <button  class="subscribe-button" type="submit"><i class="icon icon-arrowUpRight"></i></button>
                                            </div>
                                        </div>
                                        <div class="subscribe-msg"></div>
                                    </form>
                                    <div class="tf-cart-checkbox">
                                        <div class="tf-checkbox-wrapp">
                                            <input class="" type="checkbox" id="footer-Form_agree" name="agree_checkbox">
                                            <div>
                                                <i class="icon-check"></i>
                                            </div>
                                        </div>
                                        <label class="text-caption-1" for="footer-Form_agree">
                                            By clicking subcribe, you agree to the <a class="fw-6 link" href="term-of-use.html">Terms of Service</a> and <a class="fw-6 link" href="#">Privacy Policy</a>.
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="footer-bottom-wrap">
                            <div class="left">
                                <p class="text-caption-1">©2024 Dezora. All Rights Reserved.</p>
                                <div class="tf-cur justify-content-end">
                                    <div class="tf-currencies">
                                        <select class="image-select center style-default type-currencies">
                                            <option selected data-thumbnail="{% static 'web/images/country/us.svg' %}">USD</option>
                                            <option data-thumbnail="{% static 'web/images/country/vn.svg' %}">VND</option>
                                        </select>
                                    </div>
                                    <div class="tf-languages">
                                        <select class="image-select center style-default type-languages">
                                            <option>English</option>
                                            <option>Vietnam</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="tf-payment">
                                <p class="text-caption-1">Payment:</p>
                                <ul>
                                    <li>
                                        <img src="{% static 'web/images/payment/img-1.png' %}" alt="">
                                    </li>
                                    <li>
                                        <img src="{% static 'web/images/payment/img-2.png' %}" alt="">
                                    </li>
                                    <li>
                                        <img src="{% static 'web/images/payment/img-3.png' %}" alt="">
                                    </li>
                                    <li>
                                        <img src="{% static 'web/images/payment/img-4.png' %}" alt="">
                                    </li>
                                    <li>
                                        <img src="{% static 'web/images/payment/img-5.png' %}" alt="">
                                    </li>
                                    <li>
                                        <img src="{% static 'web/images/payment/img-6.png' %}" alt="">
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- /Footer -->

templates/web/partials/header.html
{% load static %}
<!-- Header -->
<header id="header" class="header-default">
    <div class="container">
        <div class="row wrapper-header align-items-center">
            <div class="col-md-4 col-3 d-xl-none">
                <a href="#mobileMenu" class="mobile-menu" data-bs-toggle="offcanvas" aria-controls="mobileMenu">
                    <i class="icon icon-categories"></i>
                </a>
            </div>
            <div class="col-xl-3 col-md-4 col-6">
                <a href="index.html" class="logo-header">
                    <img src="{% static 'web/images/logo/logo.png' %}" alt="logo" class="logo">
                </a>
            </div>
            <div class="col-xl-6 d-none d-xl-block">
                <nav class="box-navigation text-center">
                    <ul class="box-nav-ul d-flex align-items-center justify-content-center">
                        <li class="menu-item {% if is_index %}active{% endif %}"><a href="{% url 'web:index' %}" class="item-link">Home</a></li>
                        <li class="menu-item {% if is_about %}active{% endif %}"><a href="{% url 'web:about' %}" class="item-link">About</a></li>
                        <li class="menu-item {% if is_product %}active{% endif %}"><a href="{% url 'web:product' %}" class="item-link">Products</a></li>
                        <li class="menu-item {% if is_blog %}active{% endif %}"><a href="{% url 'web:blog' %}" class="item-link">Blogs</a></li>
                        <li class="menu-item {% if is_contact %}active{% endif %}"><a href="{% url 'web:contact' %}" class="item-link">Contact</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-xl-3 col-md-4 col-3">
                <ul class="nav-icon d-flex justify-content-end align-items-center">
                    <li class="nav-search"><a href="#search" data-bs-toggle="modal" class="nav-icon-item">
                        <svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M11 19C15.4183 19 19 15.4183 19 11C19 6.58172 15.4183 3 11 3C6.58172 3 3 6.58172 3 11C3 15.4183 6.58172 19 11 19Z" stroke="#181818" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M21.35 21.0004L17 16.6504" stroke="#181818" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>    
                    </a></li>
                    <li class="nav-account">
                        <a href="#" class="nav-icon-item">
                            <svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M20 21V19C20 17.9391 19.5786 16.9217 18.8284 16.1716C18.0783 15.4214 17.0609 15 16 15H8C6.93913 15 5.92172 15.4214 5.17157 16.1716C4.42143 16.9217 4 17.9391 4 19V21" stroke="#181818" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                <path d="M12 11C14.2091 11 16 9.20914 16 7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7C8 9.20914 9.79086 11 12 11Z" stroke="#181818" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </a>
                        <div class="dropdown-account dropdown-login">
                            <div class="sub-top">
                                <a href="login.html" class="tf-btn btn-reset">Login</a>
                                <p class="text-center text-secondary-2">Don’t have an account? <a href="register.html">Register</a></p>
                            </div>
                            <div class="sub-bot">
                                <span class="body-text-">Support</span>
                            </div>
                        </div>
                    </li>
                    <li class="nav-wishlist"><a href="{% url 'web:wish_list' %}" class="nav-icon-item">
                        <svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M20.8401 4.60987C20.3294 4.09888 19.7229 3.69352 19.0555 3.41696C18.388 3.14039 17.6726 2.99805 16.9501 2.99805C16.2276 2.99805 15.5122 3.14039 14.8448 3.41696C14.1773 3.69352 13.5709 4.09888 13.0601 4.60987L12.0001 5.66987L10.9401 4.60987C9.90843 3.57818 8.50915 2.99858 7.05012 2.99858C5.59109 2.99858 4.19181 3.57818 3.16012 4.60987C2.12843 5.64156 1.54883 7.04084 1.54883 8.49987C1.54883 9.95891 2.12843 11.3582 3.16012 12.3899L4.22012 13.4499L12.0001 21.2299L19.7801 13.4499L20.8401 12.3899C21.3511 11.8791 21.7565 11.2727 22.033 10.6052C22.3096 9.93777 22.4519 9.22236 22.4519 8.49987C22.4519 7.77738 22.3096 7.06198 22.033 6.39452C21.7565 5.72706 21.3511 5.12063 20.8401 4.60987V4.60987Z" stroke="#181818" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>  
                        </a>
                    </li>
                    <li class="nav-cart"><a href="#shoppingCart" data-bs-toggle="modal" class="nav-icon-item">
                        <svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M16.5078 10.8734V6.36686C16.5078 5.17166 16.033 4.02541 15.1879 3.18028C14.3428 2.33514 13.1965 1.86035 12.0013 1.86035C10.8061 1.86035 9.65985 2.33514 8.81472 3.18028C7.96958 4.02541 7.49479 5.17166 7.49479 6.36686V10.8734M4.11491 8.62012H19.8877L21.0143 22.1396H2.98828L4.11491 8.62012Z" stroke="#181818" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>  
                        <span class="count-box">1</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- /Header -->